controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_doc:
    path: /api_documentation
    controller: api_platform.swagger_ui.action