name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Clear metadata
      run: php bin/console d:s:u --force 
      
    - name: Clear console
      run: php bin/console cache:clear
      
    - name: Run Tests
      run: php bin/console phpunit
